export * from './404error'
export * from './admin/Admin.page'
export * from './FAQ'
export * from './home/home.page'
export * from './island-discover-game/island-game.page'
export * from './matching-game/matching-game.page'
export * from './PrivacyPolicy'
export * from './signin'
