export * from './404error'
export * from './admin'
export * from './dictionary'
export * from './game1'
export * from './game2'
export * from './signin'
export * from './home-page'
export * from './matching-game'